# Generated by Django 4.0.4 on 2022-05-28 17:33

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('lizgalleria', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('pic', models.ImageField(upload_to='uploads/')),
                ('landImage', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_land.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[2878, 1618], upload_to='landscape')),
                ('tallImage', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_tall.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[1618, 2878], upload_to='tall')),
                ('description', models.TextField()),
                ('image_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lizgalleria.category')),
                ('image_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lizgalleria.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
